# NICE OLED Config
## Set to n to disable slave animation
CONFIG_NICE_OLED_GEM_ANIMATION=y
## 2x slower, 30fps
CONFIG_NICE_OLED_GEM_ANIMATION_MS=1920

CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y

## LUNA
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n